version: 0.1
phases:
    install:
      commands:
        - npm install -g serverless
    pre_build:
      commands:
        - cd 'authentication'
        - cd authentication
        - cd authentication/
        
        - ls

    build:
      commands:
        - npm install
        - serverless deploy
