service: serverless-authentication-test-token # NOTE: update this with your service name

provider:
  name: aws
  stage: dev
  region: us-west-2
  runtime: nodejs4.3

functions:
  testToken:
    handler: handler.test
    events:
      - http:
          path: test-token
          method: get
          cors: true
          integration: lambda
          authorizer:
            arn: replace-with-arn-of-the-authorizer-function
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
